version: '3'
services:
  api:
    build: ./api/
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./api/.env
    volumes:
      - ./api/:/app
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=invoicing_system_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: