"""isolate association between invoice and products into invoice_item models

Revision ID: 9905e923f39d
Revises: d561e5e8309a
Create Date: 2024-12-28 19:44:07.634927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9905e923f39d'
down_revision = 'd561e5e8309a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.alter_column('unit_price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
